apiVersion: v1
kind: Secret
metadata:
  name: fidelity-secrets
type: Opaque
stringData:
  db-username: fidelity_user
  db-password: fidelity_pass
  jwt-secret: fidelity-super-secret-key-minimum-32-characters-long
