apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: portfolio-service
  ports:
    - protocol: TCP
      port: 80           # external port
      targetPort: 8081   # container port
  type: LoadBalancer     # AWS creates an ELB automatically